name: Build Psych Engine for iOS

on: workflow_dispatch

jobs:
  Build:
    name: ${{ matrix.name }}
    strategy:
      matrix:
        include:
          - name: iOS
            os: macos-14
            buildArgs: "ios -nosign"
            setupCommand: sh ./setup/unix.sh
            artifactName: iOSBuild
            artifactPath: "export/release/ios/build/Release-iphoneos/*.ipa"
            system: iOS
    uses: ./.github/workflows/build.yml
    with:
        name: ${{ matrix.name }}
        os: ${{ matrix.os }}
        buildArgs: ${{ matrix.buildArgs }}
        setupCommand: ${{ matrix.setupCommand }}
        artifactName: ${{ matrix.artifactName }}
        artifactPath: ${{ matrix.artifactPath }}
        system: ${{ matrix.system }}
